# Generated by Django 2.1.5 on 2019-03-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.IntegerField()),
                ('agent_Fname', models.CharField(max_length=50)),
                ('agent_Lname', models.CharField(max_length=50)),
                ('agent_email', models.EmailField(max_length=254)),
                ('agent_username', models.CharField(max_length=50)),
                ('agent_password', models.CharField(max_length=10)),
                ('agent_contact', models.BigIntegerField()),
                ('agent_address', models.TextField()),
                ('agent_city', models.CharField(max_length=50)),
                ('agent_state', models.CharField(max_length=50)),
                ('agent_country', models.CharField(max_length=50)),
            ],
        ),
    ]
