# Generated by Django 2.1.5 on 2019-03-16 18:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('News_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Heading', models.CharField(max_length=50)),
                ('Short_description', models.TextField()),
                ('Full_description', models.TextField()),
                ('Created_by', models.CharField(max_length=30)),
                ('Created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('Modified_by', models.CharField(max_length=30)),
                ('Modified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('Image', models.ImageField(upload_to='images/news')),
                ('Category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Catagory')),
            ],
        ),
    ]
