# Generated by Django 2.1.5 on 2019-03-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_image', models.ImageField(upload_to='image/home')),
                ('keyword', models.CharField(max_length=50)),
                ('location', models.TextField()),
                ('property_type', models.CharField(max_length=50)),
                ('property_status', models.CharField(max_length=50)),
                ('agent_name', models.CharField(max_length=50)),
                ('total_bedroom', models.IntegerField()),
                ('total_bathroom', models.IntegerField()),
                ('minimum_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maximum_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minimum_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maximum_area', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
